### ISSUE TITLE
AWSKafkaAvroConverter throwing because of "Didn't find secondary deserializer" when not trying to use Secondary deserializer

### ISSUE THREAD

**Issue by elcorbs** [awslabs/aws-glue-schema-registry#136]
_Context_

Using MSK and MSK Connect , with the confluent [S3 sink connector](https://github.com/confluentinc/kafka-connect-storage-cloud/tree/v10.0.5) and the [avro-kafkaconnect-converter](https://github.com/awslabs/aws-glue-schema-registry/tree/master/avro-kafkaconnect-converter) from this repository.
We have a producer sending messages to a topic which is a lambda function, written in Dotnet using the [confluent schema registry serdes class](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.SchemaRegistry.Serdes.AvroSerializer-1.html) to serialize the data into an Avro Generic Record.

_Issue_

The converter is throwing an error when it is trying to deserialize messages. It looks like it is trying to find the secondary deserializer but I don't want it to use a secondary deserializer and haven't provided config for one.

The stack trace
```
[Worker-] org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
--
[Worker-] 	at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.toConnectData(AWSKafkaAvroConverter.java:119)
[Worker-] 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
[Worker-] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
[Worker-] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
[Worker-] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:501)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:478)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
[Worker-] 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
[Worker-] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-] Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Didn't find secondary deserializer.
[Worker-] 	at com.amazonaws.services.schemaregistry.deserializers.SecondaryDeserializer.deserialize(SecondaryDeserializer.java:65)
[Worker-] 	at com.amazonaws.services.schemaregistry.deserializers.avro.AWSKafkaAvroDeserializer.deserializeByHeaderVersionByte(AWSKafkaAvroDeserializer.java:150)
[Worker-] 	at com.amazonaws.services.schemaregistry.deserializers.avro.AWSKafkaAvroDeserializer.deserialize(AWSKafkaAvroDeserializer.java:114)
[Worker-] 	at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.toConnectData(AWSKafkaAvroConverter.java:117)
[Worker-] 	... 18 more
[Worker-] [2022-02-03 09:26:58,641] ERROR [emma-tenure-changes-v1\|task-1] WorkerSinkTask{id=emma-tenure-changes-v1-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:191)

```

This is the config supplied to the connector
```
connector.class=io.confluent.connect.s3.S3SinkConnector
s3.region=eu-west-2
flush.size=1
schema.compatibility=BACKWARD
tasks.max=2
topics=tenure-api
storage.class=io.confluent.connect.s3.storage.S3Storage
s3.bucket.name=<bucket-name>
s3.sse.kms.key.id=<key-id>
format.class=io.confluent.connect.s3.format.parquet.ParquetFormat
partitioner.class=io.confluent.connect.storage.partitioner.DefaultPartitioner

value.converter.schemaAutoRegistrationEnabled=true
value.converter.registry.name=schema-registry
value.convertor.schemaName=tenure-api
value.converter.avroRecordType=GENERIC_RECORD
value.converter.region=eu-west-2
value.converter.schemas.enable=true
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter

key.converter=org.apache.kafka.connect.storage.StringConverter
```

Uploaded the plugin by adding the Glue Schema Registry jar file and all the jar files in the target/dependencies folder for `avro-kafkaconnect-converter` into lib, zipped it up and uploaded it S3. 

aws-glue-schema-registry v1.8.1
Kafka v2.8.1
MSK v2.7.1

**Comment by msalistra** [comment]
@elcorbs, I have encountered a similar exception.
I think the main issue here is not the secondary deserializer exception but the main one "Converting byte[] to Kafka Connect data failed due to serialization error".
The serialization that the confluent serdes class does is not compatible with the aws schema registry message format.
In the link you put from confluent it is said:
`Serialization format: byte 0: Magic byte use to identify the protocol format. bytes 1-4: Unique global id of the Avro schema that was used for encoding (as registered in Confluent Schema Registry), big endian. following bytes: The serialized data.`

It is different that the format used here below:
https://github.com/awslabs/aws-glue-schema-registry/blob/d1d3cddaa3bfcb8a8f74330c523365e8ba27cc19/common/src/main/java/com/amazonaws/services/schemaregistry/utils/AWSSchemaRegistryConstants.java#L54-L57

I think you should look for a way to implement the same as the encoder does here:
https://github.com/awslabs/aws-glue-schema-registry/blob/017fdc5840ab64f2d297d6a4babac007a7f52b4e/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/SerializationDataEncoder.java#L45-L49

**Comment by hhkkxxx133** [comment]
Yes, I agree with @msalistra. Due to the incompatible header format between Confluent and GSR, GSR library cannot deserialize directly and will look for the secondary deserializer to deserialize the message [here](https://github.com/awslabs/aws-glue-schema-registry/blob/master/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/deserializers/avro/AWSKafkaAvroDeserializer.java#L147). This can be supplied in the configuration to avoid the error. @elcorbs, does this answer your question?

**Comment by elcorbs** [comment]
Thanks @msalistra and @hhkkxxx133 for getting back to me.

We understand that the issue is being caused by different header formats between Confluent and Glue Schema Registry and that this is resulting in the secondary deserialiser error that we are seeing.

I guess our problem is that we don't understand why there is a difference between the header formats and additionally why Glue Schema Registry is incapable of decoding a standard AVRO formatted header.

Our use case is that we have a C# application which generates a schema compliant AVRO formatted payload and encodes it using a standard library for AVRO encoding, therefore generating a Confluent compliant payload that is pushed to Kafka. The C# application loads the schema via the AWS SDK and uses it for the encoding.

We are then trying to remove the payload from Kafka using MSK Connect and write the data out to S3 in Parquet format but we didn't want to write or maintain our own plugin so we tried using this plugin in conjunction with a plugin to write the data to S3.
We want to use AWS glue schema registry to decode the message so I'm unsure how using a secondary serializer would help with this.

**Comment by developerDemetri** [comment]
👋🏻  we appear to be running into the same issue as @elcorbs and @jcaberio (in #205).

We use a custom Python 3.x library [with fastavro](https://github.com/fastavro/fastavro) to serialize / deserialize Avro messages using schemas registered in Glue, but the `com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter` is not compatible with plain Avro bytes.

Are there any updates on
1) Official workarounds for messages that don't serialize messages using this Java-only SerDe
2) Configs to turn off the non-standard Avro encoding headers for Kafka Connectors?

**Comment by luizamboni** [comment]
i m stucked in the same case, but working on json schema.

**Comment by shalinibnair** [comment]
Hi, Has there been any solution for this ?

**Comment by mohitpali** [comment]
Confluent Schema Registry is a third party registry and in order to translate the messages and read from third party, we must use SecondaryDeserializer. Glue Schema Registry's default deserializer does not understand Confluent's format unless a Secondary Deserializer is provided.

Please read -

https://github.com/awslabs/aws-glue-schema-registry#migrating-from-a-third-party-schema-registry

**Comment by offline** [comment]
When setting `value.converter.secondaryDeserializer` to `io.confluent.connect.avro.AvroConverter` I receive the following error:

`com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: The secondary deserializer is not from Kafka`

What value should I use for secondaryDeserializer if my messages are encoded in Confluent's format?

**Comment by yiannis-gkoufas** [comment]
Yep, getting the same error as well when using `io.confluent.connect.avro.AvroConverter`
I can't understand why it's so difficult to integrate it.
It's just Avro, should be compatible

**Comment by talnidam** [comment]
Any solution?

**Comment by airbots** [comment]
First of all, based on the example in the repo, if we use json format and want to dump parquet. The producer needs to integrate schema in their producer record. I encounter similar error above when we deal with json to parquet output. Any followup answer for this issue?

**Comment by DenyWatanabe** [comment]
I've got a solution that works for me, may not work for everyone but maybe for some:

1. Add the following jars to the confluent S3 sink plugin /lib folder:
  - AWS Schema registry jar (I've used schema-registry-kafkaconnect-converter-1.1.23.jar)
  - Confluent server schema registry client jar (I've used confluent-7.9.1\share\java\schema-registry\kafka-schema-registry-client-7.9.1.jar)

2. Create your custom plugin using the modified zip from the previous step;

3. Your data source is probably serializing the MSK stream as avro, using the same AWS Schema registry jar above;

3. As weird as this may seem, in your S3 Sink connector configuration, select the json format class, but the connector will write AVRO files:

{
  "connector.class": "io.confluent.connect.s3.S3SinkConnector",
  "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
  "storage.class": "io.confluent.connect.s3.storage.S3Storage",
  "value.converter.schemaAutoRegistrationEnabled": "true",
  "schema.compatibility": "NONE",
  "topics.regex": ".*",
  "s3.region": "us-east-1",
  "s3.bucket.name": "your-bucket-name",
  "topics.dir": "topics",
  "flush.size": "1",
  "tasks.max": "1",
  "timezone": "UTC",
  "locale": "en-US",
  "key.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter",
  "key.converter.registry.name": "your-key-registry",
  "key.converter.schemaAutoRegistrationEnabled": "true",
  "key.converter.region": "us-east-1",
  "key.converter.compatibility": "NONE",
  "key.converter.avroRecordType": "GENERIC_RECORD",
  "value.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter",
  "value.converter.registry.name": "your-value-registry",
  "value.converter.region": "us-east-1",
  "value.converter.compatibility": "NONE",
  "value.converter.avroRecordType": "GENERIC_RECORD",
  "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
  "partition.duration.ms": "86400000",
  "path.format": "'year'=YYYY/'month'=MM/'day'=dd",
  "store.kafka.keys": "false",
  "store.kafka.headers": "false",
  "errors.log.enable": "true",
  "errors.tolerance": "all",
  "errors.log.include.messages": "true"
}
