### ISSUE TITLE
Unable to get the glue registry working with Kafka connect in a docker setup.

### ISSUE THREAD

**Issue by aleksanderaleksic** [awslabs/aws-glue-schema-registry#137]
I get this error message, and as I understand it its not able to find the schema name property.
```
java.lang.IllegalArgumentException: The validated map is empty
2022-02-05T05:22:08.438891384Z 	at org.apache.commons.lang3.Validate.notEmpty(Validate.java:352)
2022-02-05T05:22:08.438893742Z 	at org.apache.commons.lang3.Validate.notEmpty(Validate.java:374)
2022-02-05T05:22:08.438896020Z 	at com.amazonaws.services.schemaregistry.utils.GlueSchemaRegistryUtils.checkIfPresentInMap(GlueSchemaRegistryUtils.java:59)
2022-02-05T05:22:08.438908559Z 	at com.amazonaws.services.schemaregistry.utils.GlueSchemaRegistryUtils.getSchemaName(GlueSchemaRegistryUtils.java:75)
2022-02-05T05:22:08.438912642Z 	at com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer.configure(AWSKafkaAvroSerializer.java:83)
2022-02-05T05:22:08.438915327Z 	at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.configure(AWSKafkaAvroConverter.java:79)
2022-02-05T05:22:08.438917523Z 	at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:277)
2022-02-05T05:22:08.438919644Z 	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:526)
2022-02-05T05:22:08.438921750Z 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1421)
2022-02-05T05:22:08.438924023Z 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$22(DistributedHerder.java:1434)
2022-02-05T05:22:08.438926335Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-02-05T05:22:08.438928502Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-05T05:22:08.438930685Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-05T05:22:08.438932852Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Since I am using the connect docker image I use environment variables to add properties like this:
```
CONNECT_KEY_CONVERTER: com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
CONNECT_VALUE_CONVERTER: com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
CONNECT_KEY_COVERTER_REGION: us-east-1
CONNECT_VALUE_CONVERTER_REGION: us-east-1
CONNECT_KEY_COVERTER_SCHEMAAUTOREGISTRATIONENABLED: true
CONNECT_VALUE_CONVERTER_SCHEMAAUTOREGISTRATIONENABLED: true
CONNECT_KEY_COVERTER_AVRORECORDTYPE: GENERIC_RECORD
CONNECT_VALUE_CONVERTER_AVRORECORDTYPE: GENERIC_RECORD
CONNECT_KEY_COVERTER_SCHEMANAME: KeySchemaAvro
CONNECT_VALUE_CONVERTER_SCHEMANAME: ValueSchemaAvro
CONNECT_KEY_COVERTER_REGISTRY_NAME: kafka_registry
CONNECT_VALUE_CONVERTER_REGISTRY_NAME: kafka_registry
```
I think it fails because the docker image parses the env variables and adds them to the property files.
But since they are uppercased in the env variables, lowercased in the properties and this repo requires camelcase it easily gets messy.

In the readme of this repo there is this example to be used with the connector:
```
key.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
key.converter.region=ca-central-1
value.converter.region=ca-central-1
key.converter.schemaAutoRegistrationEnabled=true
value.converter.schemaAutoRegistrationEnabled=true
key.converter.avroRecordType=GENERIC_RECORD
value.converter.avroRecordType=GENERIC_RECORD
key.converter.schemaName=KeySchema
value.converter.schemaName=ValueSchema
```
but it actually ends up like this:
```
key.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
key.converter.region=ca-central-1
value.converter.region=ca-central-1
key.converter.schemaautoregistrationenabled=true
value.converter.schemaautoregistrationenabled=true
key.converter.avrorecordtype=GENERIC_RECORD
value.converter.avrorecordtype=GENERIC_RECORD
key.converter.schemaname=KeySchema
value.converter.schemaname=ValueSchema
```

Just wondering if there is anything else I can do to make this work?
Could it be a solution to ignore the casing of the properties that are camelcased?

**Comment by aleksanderaleksic** [comment]
This is what the confluent documentation sais about property ENV var convertion:

[https://docs.confluent.io/platform/current/installation/docker/config-reference.html#kconnect-long-configuration](https://docs.confluent.io/platform/current/installation/docker/config-reference.html#kconnect-long-configuration)

**Comment by OneCricketeer** [comment]
Unfortunately, Java properties are case-sensitive, and the environment variables for the Confluent container will always be lowercased. 

The work-around would be to instead HTTP POST the configurations you need for the specific connector rather than try to apply them at the worker level.
