### ISSUE TITLE
Failed to construct kafka consumer when trying avro-kafkaconnect-converter with Kafka Connect BigQuery

### ISSUE THREAD

**Issue by mezig351** [awslabs/aws-glue-schema-registry#164]
Hi,

I am trying to use glue schema registry with Avro, and [Kafka Connect BigQuery](https://github.com/confluentinc/kafka-connect-bigquery) with Docker, using the base image from `bitnami/kafka:2.6.0`.

When I follow the steps from documentation, (by the way maven build doesn't work inside build-tools repo, as it adds `build-repo` twice to the path, and this is different in [documentation ](https://docs.aws.amazon.com/glue/latest/dg/schema-registry-integrations.html#schema-registry-integrations-apache-kafka-connect) vs [ReadMe](https://github.com/awslabs/aws-glue-schema-registry#using-kafka-connect-with-aws-glue-schema-registry))

I get the following error, and kafka-connect is not able to start:
```
[2022-04-20 11:02:32,526] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed:84)
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.<init>(WorkerGroupMember.java:159)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(DistributedHerder.java:232)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(DistributedHerder.java:196)
        at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:125)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:78)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.kafka.clients.NetworkClient.<init>(org.apache.kafka.common.network.Selectable, org.apache.kafka.clients.Metadata, java.lang.String, int, long, long, int, int, int, org.apache.kafka.clients.ClientDnsLookup, org.apache.kafka.common.utils.Time, boolean, org.apache.kafka.clients.ApiVersions, org.apache.kafka.common.utils.LogContext)'
        at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.<init>(WorkerGroupMember.java:126)
        ... 4 more
[2022-04-20 11:02:32,539] WARN  (org.eclipse.jetty.server.AbstractConnector:372)
java.io.IOException: Thread signal failed
        at java.base/sun.nio.ch.NativeThread.signal(Native Method)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:365)
        at java.base/java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:242)
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:112)
        at org.eclipse.jetty.server.ServerConnector.close(ServerConnector.java:368)
        at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:104)
        at org.eclipse.jetty.server.Server.doStop(Server.java:428)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:127)
[2022-04-20 11:03:32,574] INFO Stopped http_8083@67e0ff3a{HTTP/1.1,[http/1.1]}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector:380)
```
I tried matching kafka versions in pom files for `kafka-bigquery-connect`(2.5.0 -> 2.8.1) and `aws-glue-schema-registry` (2.8.1). I tried saving the jar files from `aws-glue-schema-registry` to the same `plugin.path` that `worker.properties` looks at. Neither worked. I'd appreciate any help.

Thanks!

**Comment by mezig351** [comment]
`bitnami/kafka:2.8.1` resolved the issue
