### ISSUE TITLE
Deserialization errors when using Kinesis to MSK connector

### ISSUE THREAD

**Issue by jcaberio** [awslabs/aws-glue-schema-registry#205]
We have a legacy app that's already streaming data to Kinesis. We used [camel-aws2-kinesis-kafka-connector](https://camel.apache.org/camel-kafka-connector/0.11.x/reference/connectors/camel-aws2-kinesis-kafka-source-connector.html) to ingest data from Kinesis to MSK.

![legacy-and-new-architecture](https://user-images.githubusercontent.com/21195237/183073212-12c27e2f-e098-4b4a-b1e5-2550834af212.png)

The new system will then consume messages from MSK and do some processing. We are using [AWS Glue Schema Registry](https://docs.aws.amazon.com/glue/latest/dg/schema-registry.html) in the consumer app as follows

```
props.put(AWSSchemaRegistryConstants.DATA_FORMAT, DataFormat.JSON.name());
props.put(AWSSchemaRegistryConstants.AWS_REGION, REGION);
props.put(AWSSchemaRegistryConstants.REGISTRY_NAME, REGISTRY_NAME);
props.put(AWSSchemaRegistryConstants.SCHEMA_NAME, SCHEMA_NAME);

props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, GlueSchemaRegistryKafkaDeserializer.class.getName());

try (final KafkaConsumer<String, JsonDataWithSchema> consumer = new KafkaConsumer<>(props)) {
    consumer.subscribe(Collections.singletonList(topic));
    while (true) {
        final ConsumerRecords<String, JsonDataWithSchema> records = consumer.poll(100);
        for (final ConsumerRecord<String, JsonDataWithSchema> record : records) {
            final String key = record.key();
            final JsonDataWithSchema value = record.value();
            final long ts = record.timestamp();
            log.info("timestamp: {} key: {} value: {}", new Date(ts), key, value);
        }
    }
}
```

We encountered the following errors when we run our app

```
Exception in thread "main" org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition kinesis.json-3 at offset 158. If needed, please seek past the record to continue consumption.
    at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1435)
    at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133)
    at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1658)
    at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1494)
    at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:716)
    at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:682)
    at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1168)
    at com.paymaya.risktech.P2PConsumer.main(P2PConsumer.java:53)
Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Didn't find secondary deserializer.
    at com.amazonaws.services.schemaregistry.deserializers.SecondaryDeserializer.deserialize(SecondaryDeserializer.java:65)
    at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer.deserializeByHeaderVersionByte(GlueSchemaRegistryKafkaDeserializer.java:161)
    at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer.deserialize(GlueSchemaRegistryKafkaDeserializer.java:116)
    at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
    at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1426)
```

The data in the topic follows the format that we specified in the schema registry. Is this issue related to #136?

**Comment by allkliu** [comment]
It seems like your original message encoded by the legacy app or the camel connector is not compatible with GSR - could you provide some clarity on how you intend to use our service? This may be happening because you aren't using the GSR serializer, similar to the issue you refer to.

**Comment by blacktooth** [comment]
Please let us know if this is still an issue.

**Comment by vanessapinto257** [comment]
Please feel free to reopen if this is still an issue
