### ISSUE TITLE
Issue when extending Confluent's Kafka Connect Docker images

### ISSUE THREAD

**Issue by zevektor** [awslabs/aws-glue-schema-registry#226]
Hi,

I am trying to install the Avro Converter inside the connect docker image by extending it. 
To do so, I am using the following command in the dockerfile:

> ENV GLUE_SCHEMA_REGISTRY_VERSION="1.1.14"
> 
> RUN wget -O /usr/share/java/schema-registry-kafkaconnect-converter.jar "https://repo1.maven.org/maven2/software/amazon/glue/schema-registry-kafkaconnect-converter/${GLUE_SCHEMA_REGISTRY_VERSION}/schema-registry-kafkaconnect-converter-${GLUE_SCHEMA_REGISTRY_VERSION}.jar" && \
>     cp /usr/share/java/schema-registry-kafkaconnect-converter.jar /usr/share/java/cp-base-new/ && \
>     cp /usr/share/java/schema-registry-kafkaconnect-converter.jar /etc/kafka-connect/jars/ && \
>     rm /usr/share/java/schema-registry-kafkaconnect-converter.jar

But when the worker launches, I am getting the following error: 

> ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed)
> java.lang.NoSuchMethodError: 'boolean org.apache.kafka.common.utils.Utils.isBlank(java.lang.String)'
>     at org.apache.kafka.connect.runtime.WorkerConfig$ListenersValidator.ensureValid(WorkerConfig.java:429)
>     at org.apache.kafka.common.config.ConfigDef$ConfigKey.<init>(ConfigDef.java:1150)
>     at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:152)
>     at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:172)
>     at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:211)
>     at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:373)
>     at org.apache.kafka.connect.runtime.WorkerConfig.baseConfigDef(WorkerConfig.java:252)
>     at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<clinit>(DistributedConfig.java:196)
>     at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:95)
>     at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)

Which suggests that there is some kind of conflict with commons-lang3 library. 

Is there a way to avoid this?

**Comment by OneCricketeer** [comment]
`org.apache.kafka.common.utils.Utils` is part of `kafka-clients`, not commons lang3
