### ISSUE TITLE
GSR Avro Converter library fails with FilePulseConnector

### ISSUE THREAD

**Issue by kalyanjanaki777** [awslabs/aws-glue-schema-registry#260]
My Cx is trying to use Glue Schema Registry on MSK Connect with "[FilePulsConnector](https://github.com/streamthoughts/kafka-connect-file-pulse)". The connector works fine without GSR library on MSK Connect but fails with below error when tried to use with GSR.

```
"[Worker-0a883fbe2e2d8ef0f] Caused by: java.io.EOFException: HttpConnectionOverHTTP@74bdca2d::SocketChannelEndPoint@72ae7530{l=/INTERNAL_IP,r=/INTERNAL_IP,ISHUT,fill=-,flush=-,to=5074/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@74bdca2d(l:/INTERNAL_IP <-> r:/INTERNAL_IP,closed=false)=>HttpChannelOverHTTP@259db583(exchange=HttpExchange@725a42a8{req=HttpRequest[PUT /connectors/schema-support-test/config HTTP/1.1]@68ac026c[TERMINATED/null] res=HttpResponse[null 0 null]@69aafdbc[PENDING/null]})[send=HttpSenderOverHTTP@21d36ca7(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@13c2537{s=START}],recv=HttpReceiverOverHTTP@98be81e(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]"
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:376)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1614)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:259)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:181)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:169)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
[Worker-0a883fbe2e2d8ef0f] 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
```

**Comment by blacktooth** [comment]
Do you see any specific errors from GSR library? Do you suspect this could be due to any class conflicts between [FilePulsConnector](https://github.com/streamthoughts/kafka-connect-file-pulse) and GSR library?
