### ISSUE TITLE
GSR if falling to parse a MAP attribute in AVRO schema

### ISSUE THREAD

**Issue by waytoharish** [awslabs/aws-glue-schema-registry#261]
Hi Team,
I am facing a weird issue while trying to use the GSR with MSK Connect for io.debezium.connector.mongodb.MongoDbConnector.    I am doing DB.insert with below record which not register any schema in the GSR
db.getCollection("availabilities4").insert({
    
     "propertyId" : NumberLong(1111),
    "ratePlanExtId" : "BAR2",
    "channelId" : NumberLong(33),
    "roomTypeExtId" : "RT1",
    "year" : 2025,
    "month" : 2,
    "createdDate" : ISODate("2023-04-21T06:11:03.785Z"),

   "dayAvailability" : {
        "25" : 30
        
    },
   
    "modifiedDate" : ISODate("2023-04-21T06:11:03.785Z"),
    "processStartDate" : ISODate("2023-04-21T06:11:03.744Z")
    
})

As soon I remove from the record and try to insert the record I can see Schema got registered in GSR
"dayAvailability" : {
        "25" : 30
        
    }, 
    
    
 I see following error-
 
 
uting stage 'VALUE_CONVERTER' with class 'com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter', where source record is = SourceRecord{sourcePartition={rs=rs0, server_id=msk}, sourceOffset={sec=1683555581, ord=1, transaction_id=null, resume_token=82645904FD000000012B022C0100296E5A10048CA74D1DCD6B414698893087B5AF261F46645F69640064645904FDDD9CB67DD0415D470004}} ConnectRecord{topic='msk.dpapr-db.availabilities5', kafkaPartition=null, key=Struct{id={"$oid": "645904fddd9cb67dd0415d47"}}, keySchema=Schema{msk.dpapr_db.availabilities5.Key:STRUCT}, value=Struct{after={"_id": {"$oid": "645904fddd9cb67dd0415d47"},"propertyId": {"$numberLong": "1111"},"ratePlanExtId": "BAR2","channelId": {"$numberLong": "33"},"roomTypeExtId": "RT1","year": 2025,"month": 2,"createdDate": {"$date": 1682057463785},"dayAvailability": {"25": 30},"modifiedDate": {"$date": 1682057463785},"processStartDate": {"$date": 1682057463744}},source=Struct{version=2.1.2.Final,connector=mongodb,name=msk,ts_ms=1683555581000,db=dpapr-db,rs=rs0,collection=availabilities5,ord=1},op=c,ts_ms=1683555581602}, valueSchema=Schema{msk.dpapr_db.availabilities5.Envelope:STRUCT}, timestamp=null, headers=ConnectHeaders(headers=)}. (org.apache.kafka.connect.runtime.errors.LogReporter:66)
org.apache.avro.SchemaParseException: Illegal initial character: 25
	at org.apache.avro.Schema.validateName(Schema.java:1567)
	at org.apache.avro.Schema.access$400(Schema.java:92)
	at org.apache.avro.Schema$Field.<init>(Schema.java:549)
	at org.apache.avro.Schema$Field.<init>(Schema.java:588)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.addAvroRecordField(AvroData.java:1050)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchema(AvroData.java:883)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchemaWithCycle(AvroData.java:1030)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchema(AvroData.java:866)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.addAvroRecordField(AvroData.java:1050)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchema(AvroData.java:883)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchema(AvroData.java:706)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectSchema(AvroData.java:700)
	at com.amazonaws.services.schemaregistry.kafkaconnect.avrodata.AvroData.fromConnectData(AvroData.java:337)
	at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.fromConnectData(AWSKafkaAvroConverter.java:94)
	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:64)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.lambda$convertTransformedRecord$9(AbstractWorkerSourceTask.java:495)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:183)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:217)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:159)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.convertTransformedRecord(AbstractWorkerSourceTask.java:495)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.sendRecords(AbstractWorkerSourceTask.java:390)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:357)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Here is the same schema work fine with    com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter

Auto Created Schema for JSON Converter is 

{"type":"object","connect.name":"com.ibsplc.demandgateway.common.vo.avro.availability.HotelAvailability","properties":{"createdDate":{"connect.index":6,"oneOf":[{"type":"integer","connect.index":6,"connect.version":1,"connect.type":"int64","connect.name":"org.apache.kafka.connect.data.Timestamp"},{"type":"null"}]},"month":{"connect.index":4,"oneOf":[{"type":"integer","connect.index":4,"connect.type":"int32"},{"type":"null"}]},"year":{"connect.index":4,"oneOf":[{"type":"integer","connect.index":4,"connect.type":"int32"},{"type":"null"}]},"modifiedDate":{"connect.index":6,"oneOf":[{"type":"integer","connect.index":6,"connect.version":1,"connect.type":"int64","connect.name":"org.apache.kafka.connect.data.Timestamp"},{"type":"null"}]},"ratePlanExtId":{"connect.index":1,"oneOf":[{"type":"string","connect.index":1},{"type":"null"}]},"propertyId":{"connect.index":0,"oneOf":[{"type":"integer","connect.index":0,"connect.type":"int64"},{"type":"null"}]},"processStartDate":{"connect.index":6,"oneOf":[{"type":"integer","connect.index":6,"connect.version":1,"connect.type":"int64","connect.name":"org.apache.kafka.connect.data.Timestamp"},{"type":"null"}]},"channelId":{"connect.index":0,"oneOf":[{"type":"integer","connect.index":0,"connect.type":"int64"},{"type":"null"}]},"roomTypeExtId":{"connect.index":1,"oneOf":[{"type":"string","connect.index":1},{"type":"null"}]},"dayAvailability":{"connect.index":7,"oneOf":[{"type":"null"},{"type":"object","connect.name":"msk.dpapr_db.availabilities5.dayAvailability","properties":{"25":{"connect.index":0,"oneOf":[{"type":"integer","connect.index":0,"connect.type":"int32"},{"type":"null"}]}}}]}}

**Comment by YangSan0622** [comment]
I have looked into this issue, I think the problem here is Avro does not allow field name starts with number. Please refer to https://avro.apache.org/docs/1.8.1/spec.html#names
Whereas in this case, one of the field name is `25`, which causes conversion failure. There is nothing we can do in GSR converter as we should not modify the field name during conversion.

Our suggestion here is to rename the field to meet Avro specification if you are interested in using Avro format.
