### ISSUE TITLE
Authentication issue on MSK Connect

### ISSUE THREAD

**Issue by GergelyKalmar** [awslabs/aws-glue-schema-registry#265]
I'm trying to use this library with MSK Connect with the following worker configuration:

```
key.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
key.converter.region=us-east-1
key.converter.schemaAutoRegistrationEnabled=true
key.converter.avroRecordType=GENERIC_RECORD
key.converter.registry.name=app-core-cdc
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
value.converter.region=us-east-1
value.converter.schemaAutoRegistrationEnabled=true
value.converter.avroRecordType=GENERIC_RECORD
value.converter.registry.name=app-core-cdc
schema.name.adjustment.mode=avro
config.providers=secretManager
config.providers.secretManager.class=com.github.jcustenborder.kafka.config.aws.SecretsManagerConfigProvider
config.providers.secretManager.param.aws.region=us-east-1
offset.storage.topic=__amazon_msk_connect_offsets_debezium
offset.storage.replication.factor=3
offset.flush.timeout.ms=15000
offset.flush.interval.ms=30000
```

I've followed the steps in the [documentation](https://github.com/awslabs/aws-glue-schema-registry#using-kafka-connect-with-aws-glue-schema-registry) up until the "Add command below to Launch mode section" point and copied the `avro-kafkaconnect-converter`, `common`, `jsonschema-kafkaconnect-converter`, `serializer-deserializer`, `serializer-deserializer-msk-iam` and `target` folders into the MSK Connect plugin ZIP.

However, when starting the connector I'm getting the following error:

```
[Worker-092a3c2ae69e2f48d] java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1006)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:313)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1075)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1317)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1260)
[Worker-092a3c2ae69e2f48d] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-092a3c2ae69e2f48d] Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:228)
[Worker-092a3c2ae69e2f48d] 	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
[Worker-092a3c2ae69e2f48d] 	... 8 more
[Worker-092a3c2ae69e2f48d] Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
[Worker-092a3c2ae69e2f48d] Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism AWS_MSK_IAM
```

When using the standard JSON converters everything works smoothly, the connector produces the correct events in the appropriate MSK topics:
```
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
```

Any suggestions for resolving this error? Note that for the Debezium schema history topic I've been using the following configuration successfully:
```
    "schema.history.internal.producer.security.protocol" = "SASL_SSL"
    "schema.history.internal.producer.sasl.mechanism" = "AWS_MSK_IAM"
    "schema.history.internal.producer.sasl.jaas.config" = "software.amazon.msk.auth.iam.IAMLoginModule required;"
    "schema.history.internal.producer.sasl.client.callback.handler.class" = "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
```

Do I perhaps needs to adjust the worker configuration further somehow so it works with Glue Schema Registry?

**Comment by GergelyKalmar** [comment]
It seems that the issue can be resolved by excluding the "serializer-deserializer-msk-iam" folder from the MSK connect plugin zip file. The documentation should definitely mention this though.
