### ISSUE TITLE
JSON schema evaluation fails for Kafka Source Connector

### ISSUE THREAD

**Issue by raipragyaa** [awslabs/aws-glue-schema-registry#268]
Hello, I am using this library with Kafka source connect. Below are my Kafka connect worker configurations - 
```
    "key.converter.region"                        = "us-east-1"
    "key.converter.registry.name"                 = var.schema_registry_name
    "key.converter.compatibility"                 = "FULL"
    "key.converter.schemaAutoRegistrationEnabled" = true
    "key.converter.dataFormat"="JSON"
    "key.converter.avroRecordType"="GENERIC_RECORD"
    "key.converter.schemaNameGenerationClass" = "<CustomNamingStrategyClass>"
    "value.converter.region"                        = "us-east-1"
    "value.converter.registry.name"                 = var.schema_registry_name
    "value.converter.compatibility"                 = "FULL"
    "value.converter.schemaAutoRegistrationEnabled" = true
    "value.converter.dataFormat"="JSON"
    "value.converter.avroRecordType"="GENERIC_RECORD"
    "key.converter.schemaNameGenerationClass" = "<CustomNamingStrategyClass>"
```
As you see, compatibility mode has been set to `FULL` but updating my source db table with any optional field gives me error saying `Schema Evolution Failed`.  I have also tries most of the compatibility modes but end up getting same issue.
Here is the stack trace of the error - 

```
[Worker-0acd35d51b07406e0] Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Failed to get schemaVersionId by schema definition for schema name = users
--
[Worker-0acd35d51b07406e0] 	at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getSchemaVersionIdByDefinition(AWSSchemaRegistryClient.java:148)
[Worker-0acd35d51b07406e0] 	at com.amazonaws.services.schemaregistry.common.SchemaByDefinitionFetcher$SchemaDefinitionToVersionCache.load(SchemaByDefinitionFetcher.java:110)
[Worker-0acd35d51b07406e0] 	at com.amazonaws.services.schemaregistry.common.SchemaByDefinitionFetcher$SchemaDefinitionToVersionCache.load(SchemaByDefinitionFetcher.java:106)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[Worker-0acd35d51b07406e0] 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[Worker-0acd35d51b07406e0] 	at com.amazonaws.services.schemaregistry.common.SchemaByDefinitionFetcher.getORRegisterSchemaVersionId(SchemaByDefinitionFetcher.java:74)
[Worker-0acd35d51b07406e0] 	... 18 more
[Worker-0acd35d51b07406e0] Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Schema Found but status is FAILURE
```

I tried using AVRO converter with the same worker properties and it allows me update the source table with optional fields. I was able to get the updated data in the topic.

Is there any property I am missing for JSON schema, or it's not supported?

**Comment by y-lahrichi** [comment]
I am having a similar issue, except my error at the bottom of the stack trace is: 

[Worker-0dabc170e2f071b0e] Caused by: software.amazon.awssdk.services.glue.model.EntityNotFoundException: Schema version is not found. (Service: Glue, Status Code: 400, Request ID: <_requestID_>),

 even though its clearly there by the name that they show one error up...

**Comment by blacktooth** [comment]
The compatibility rules can vary between data formats. Without the schema, it is hard to debug the compatibility rule. Can you please provide a simplified version of the schema you are trying to use? Also, Full is more restrictive compatibility mode as it mandates the changes to be both forward and backward compatible.
