### ISSUE TITLE
ConnectSchemaToProtobufSchemaConverter throws NullPointerException

### ISSUE THREAD

**Issue by mdimas** [awslabs/aws-glue-schema-registry#289]
I'm using the Debezium connector with ProtobufSchemaConverter as the value converter and auto-registering schema in Glue. It's unclear what is actually the source of the null value.

```
Caused by: java.lang.NullPointerException
  at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.FieldBuilder.build(FieldBuilder.java:92)
  at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter.buildMessageDescriptorProto(ConnectSchemaToProtobufSchemaConverter.java:81)
  at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter.buildFileDescriptorProto(ConnectSchemaToProtobufSchemaConverter.java:66)
  at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter.convert(ConnectSchemaToProtobufSchemaConverter.java:41)
  at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.fromConnectData(ProtobufSchemaConverter.java:105)
  at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$3(WorkerSourceTask.java:321)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190
```

**Comment by jvdadda** [comment]
Fixed in PR #518. The NPE occurs because `fieldSchema.parameters()` can return `null` for STRUCT-type fields that don't carry protobuf metadata (e.g., from Debezium). The fix adds null guards for both `fieldSchema.parameters()` and `fieldSchema.name()` in `FieldBuilder.build()`.

cc @knoxy5467 @swaradgat19 @stvbrad @blacktooth
