### ISSUE TITLE
Protobuf converter doesn't sanitize schema/field names

### ISSUE THREAD

**Issue by mdimas** [awslabs/aws-glue-schema-registry#290]
I'm working on the Debezium CDC connector working with AWS Glue as my schema registry using protobuf. It currently gets an identifier error in the field builder.
```
Caused by: com.google.protobuf.Descriptors$DescriptorValidationException:com.amazonaws.services.schemaregistry.kafkaconnect.autogenerated.debezium.database_name.table_name.Value.debezium.database_name.table_name.Value: \"debezium.database_name.table_name.Value\" is not a valid identifier. at com.google.protobuf.Descriptors$DescriptorPool.validateSymbolName(Descriptors.java:2703) at com.google.protobuf.Descriptors$DescriptorPool.addSymbol(Descriptors.java:2575) at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:971) at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:648) at com.google.protobuf.Descriptors$FileDescriptor.<init>(Descriptors.java:548) at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:319) at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:290) at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter.buildFileDescriptor(ConnectSchemaToProtobufSchemaConverter.java:88) at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter.convert(ConnectSchemaToProtobufSchemaConverter.java:43) at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.fromConnectData(ProtobufSchemaConverter.java:105) at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63) at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$3(WorkerSourceTask.java:321)
```

The connector works with Confluence's protobuf converter. I'm working on modifying the connector configuration to modify the name, but it seems like it would be good for the AWS converter to sanitize the names the same way the Confluence one does.

**Comment by jvdadda** [comment]
Hi @mdimas, this is fixed in our maintained fork of the Java library, in https://github.com/mobsuccess-devops/aws-glue-schema-registry/pull/181, the third piece of the Debezium-to-Protobuf path after the STRUCT-without-metadata guards from #289. The converter used the Connect schema name verbatim as the Protobuf message name and derived the file package from it, so a dotted Debezium name such as `server.database.table.Value` failed descriptor validation exactly as in your trace, and a hyphenated server name failed the same way through the package. Every emitted name now goes through the same rule Confluent's converter applies (any character outside `[A-Za-z0-9_]` becomes `_`, a leading digit gets a `_` prefix), the top-level message takes the schema's simple name, and references are sanitized in the same pass; names that were already valid are unchanged. It is available in the latest published release, currently 4.1.0, on Maven Central as `com.mobsuccess:protobuf-kafkaconnect-converter`; Connect workers take the `-plugin.zip` attached to the release.

Upstream is releasing again and this is not in its 2.0.0; we're happy to contribute it back.
