### ISSUE TITLE
`NoSuchMethodError` from `GlueSchemaRegistryDeserializerDataParser` when running on JDK 8

### ISSUE THREAD

**Issue by richardfearn** [awslabs/aws-glue-schema-registry#322]
We recently upgraded from `schema-registry-serde` 1.1.16 to 1.1.17 and started seeing errors from `GlueSchemaRegistryDeserializerDataParser`:

```
 java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializerDataParser.getHeaderVersionByte(GlueSchemaRegistryDeserializerDataParser.java:223)
	at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer.getHeaderVersionByte(GlueSchemaRegistryKafkaDeserializer.java:166)
	at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer.deserialize(GlueSchemaRegistryKafkaDeserializer.java:115)
        [...]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
        [...]
```

Is this project now being compiled with a JDK > 8? That might explain why the class files now refer to a `rewind` method that returns `ByteBuffer` (which was added in JDK 9):

```
   public java.lang.Byte getHeaderVersionByte(java.nio.ByteBuffer);
     descriptor: (Ljava/nio/ByteBuffer;)Ljava/lang/Byte;
     flags: ACC_PUBLIC
     Code:
       stack=1, locals=3, args_size=2
          0: aload_1
-         1: invokevirtual #5                  // Method java/nio/ByteBuffer.rewind:()Ljava/nio/Buffer;
+         1: invokevirtual #5                  // Method java/nio/ByteBuffer.rewind:()Ljava/nio/ByteBuffer;
          4: pop
          5: aload_1
          6: invokevirtual #6                  // Method java/nio/ByteBuffer.slice:()Ljava/nio/ByteBuffer;
          9: astore_2
         10: aload_2
         11: invokevirtual #8                  // Method java/nio/ByteBuffer.get:()B
         14: invokestatic  #22                 // Method java/lang/Byte.valueOf:(B)Ljava/lang/Byte;
         17: areturn
       LineNumberTable:
         line 223: 0
         line 224: 5
         line 226: 10
       LocalVariableTable:
         Start  Length  Slot  Name   Signature
             0      18     0  this   Lcom/amazonaws/services/schemaregistry/deserializers/GlueSchemaRegistryDeserializerDataParser;
             0      18     1 byteBuffer   Ljava/nio/ByteBuffer;
            10       8     2 slicedBuffer   Ljava/nio/ByteBuffer;
```

However I noticed that the README says:

> Minimum requirements — To use the AWS Glue Schema Registry, you'll need Java > 1.8 and < Java 15.

...and [has done](https://github.com/awslabs/aws-glue-schema-registry/commit/a7017fb7a418f30d6302d3822e3464388228a72c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17) since the [1.1.0 release](https://github.com/awslabs/aws-glue-schema-registry/releases/tag/v1.1.0) in June 2021.

**Comment by YangSan0622** [comment]
Yes, it was not compiled with Java 8, sorry about the issue. We have noticed this and planning on releasing 1.1.18 shortly and it will be compiled with Java 8.

**Comment by YangSan0622** [comment]
v1.1.18 is released, the error should go away if you use the latest version. Thank you!
