### ISSUE TITLE
v1.1.17 to v1.1.19 fails producing messages with error "java.lang.NoSuchFieldError: IDENTITY_PROVIDERS" on SelfManaged Kafka server with no authentication

### ISSUE THREAD

**Issue by bjanischevsky** [awslabs/aws-glue-schema-registry#337]
When producing a message against a SelfManaged Kafka server with no authentication with version 1.1.17 to 1.1.18 I get the error below. I am forced for now to use 1.1.16 only.

Failed to construct kafka producer Exception Stacktrace: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:439)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:290)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:317)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:302)
	at xtb.postevents.infrastructure.AppKafkaProducer.ProduceAvroMessage(AppKafkaProducer.java:226)
	at xtb.postevents.infrastructure.AppKafkaProducer.SendMessage(AppKafkaProducer.java:62)
	at xtb.postevents.handlers.PostMessageHandler.handle(PostMessageHandler.java:28)
	at xtb.postevents.HttpHandler.handleRequest(HttpHandler.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:378)
	at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:905)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:245)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:197)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:187)
Caused by: java.lang.NoSuchFieldError: IDENTITY_PROVIDERS
	at software.amazon.awssdk.services.glue.DefaultGlueBaseClientBuilder.finalizeServiceConfiguration(DefaultGlueBaseClientBuilder.java:76)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:182)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:180)
	at software.amazon.awssdk.services.glue.DefaultGlueClientBuilder.buildClient(DefaultGlueClientBuilder.java:37)
	at software.amazon.awssdk.services.glue.DefaultGlueClientBuilder.buildClient(DefaultGlueClientBuilder.java:25)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:147)
	at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.<init>(AWSSchemaRegistryClient.java:116)
	at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializationFacade.<init>(GlueSchemaRegistrySerializationFacade.java:69)
	at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializationFacade$GlueSchemaRegistrySerializationFacadeBuilder.build(GlueSchemaRegistrySerializationFacade.java:48)
	at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer.configure(GlueSchemaRegistryKafkaSerializer.java:96)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:375)
	... 16 more

**Comment by bjanischevsky** [comment]
This issue solves itself by using all latest AWS dependencies:
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-core</artifactId>
      <version>1.2.3</version>
    </dependency>

    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-events</artifactId>
      <version>3.11.4</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.msk</groupId>
      <artifactId>aws-msk-iam-auth</artifactId>
      <version>2.0.3</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.glue</groupId>
      <artifactId>schema-registry-serde</artifactId>
      <version>1.1.19</version>
    </dependency>

    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-clients</artifactId>
      
      <version>3.7.0</version>
    </dependency>

    <dependency>
      <groupId>io.confluent</groupId>
      <artifactId>kafka-avro-serializer</artifactId>
      <version>7.6.0</version>
    </dependency>

    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.25.3</version>
    </dependency>

**Comment by bjanischevsky** [comment]
Closed.
