### ISSUE TITLE
Nested Protobuf Message with oneof fails to convert

### ISSUE THREAD

**Issue by metropolis-ameer** [awslabs/aws-glue-schema-registry#347]
Example proto
```
message SourceMetadata {
  string source_id = 1;
  oneof source {
    string registered = 2;
    string unregistered = 3;
  }
}

message Eventr {
  SourceMetadata source_meta = 1;
  event_id = 2;
}
```
Producing and consuming records serialized by this proto in an application works fine.
Consuming an Eventr record serialized by this proto with an MSK connect connector fails to create the connect schema from the proto correctly.  For the record below, the error would show
```
<html><head></head><body>
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Error converting value: "source_id: "TEST1717029245841207579"
[Worker-0504c2846446741d1] registered: user123
[Worker-0504c2846446741d1] " (Java Type: class com.google.protobuf.DynamicMessage, Protobuf type: MESSAGE) to Connect type: STRUCT
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectDataField(ProtobufDataToConnectDataConverter.java:101)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectData(ProtobufDataToConnectDataConverter.java:67)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.toConnectData(ProtobufSchemaConverter.java:122)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
[Worker-0504c2846446741d1] 	... 13 more
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "unregistered", schema type: STRING
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.validate(Struct.java:233)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:253)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)

</body></html><html><head></head><body>
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Error converting value: "source_id: "TEST1717029245841207579"
--
[Worker-0504c2846446741d1] version: "5.4.0"
[Worker-0504c2846446741d1] serial_number: "TEST1717029245841207579"
[Worker-0504c2846446741d1] registration_id: "dd1156d5-b18b-32e6-9c0b-857ce97d9126"
[Worker-0504c2846446741d1] registered: SOURCE_ORION
[Worker-0504c2846446741d1] " (Java Type: class com.google.protobuf.DynamicMessage, Protobuf type: MESSAGE) to Connect type: STRUCT
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectDataField(ProtobufDataToConnectDataConverter.java:101)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectData(ProtobufDataToConnectDataConverter.java:67)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.toConnectData(ProtobufSchemaConverter.java:122)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
[Worker-0504c2846446741d1] 	... 13 more
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "unregistered", schema type: STRING
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.validate(Struct.java:233)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:253)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)

</body></html><html><head></head><body>
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Error converting value: "source_id: "TEST1717029245841207579"
--
[Worker-0504c2846446741d1] version: "5.4.0"
[Worker-0504c2846446741d1] serial_number: "TEST1717029245841207579"
[Worker-0504c2846446741d1] registration_id: "dd1156d5-b18b-32e6-9c0b-857ce97d9126"
[Worker-0504c2846446741d1] registered: SOURCE_ORION
[Worker-0504c2846446741d1] " (Java Type: class com.google.protobuf.DynamicMessage, Protobuf type: MESSAGE) to Connect type: STRUCT
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectDataField(ProtobufDataToConnectDataConverter.java:101)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.toconnectdata.ProtobufDataToConnectDataConverter.toConnectData(ProtobufDataToConnectDataConverter.java:67)
[Worker-0504c2846446741d1] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.toConnectData(ProtobufSchemaConverter.java:122)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
[Worker-0504c2846446741d1] 	... 13 more
[Worker-0504c2846446741d1] Caused by: org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "unregistered", schema type: STRING
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.validate(Struct.java:233)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:253)
[Worker-0504c2846446741d1] 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)

</body></html>
```

```
{
source_meta = {
  source_id = "TEST1717029245841207579"
  registered = "user123"
}
event_id = "123-213-321dj"
}
```

**Comment by jvdadda** [comment]
Hi @metropolis-ameer, this is fixed in our maintained fork of the Java library, in https://github.com/mobsuccess-devops/aws-glue-schema-registry/pull/183. The cause matched your example exactly: the converter grouped a `oneof` into an optional struct only for the top-level message, while a nested message such as `SourceMetadata` went through a different path that turned every branch into a required Connect field. Since at most one branch is ever set, the first record failed on the unset one. Nested messages now go through the same grouping as the top level, at any depth, with your shape (a `oneof` inside a message inside the record) as the regression proto. It is available in the latest published release, currently 4.1.0, on Maven Central as `com.mobsuccess:protobuf-kafkaconnect-converter`; Connect workers take the `-plugin.zip` attached to the release.

If upstream picks back up, we're happy to contribute this back.
