### ISSUE TITLE
Produce Kafka Avro records using glue schema registry

### ISSUE THREAD

**Issue by skydeep-9** [awslabs/aws-glue-schema-registry#37]
Failing to get Kafka producer working with AWSSchemaRegistry, not able to connect to the SchemaRegistry. 

The configuration for the `AWSKafkaAvroSerializer` is listed below, with stacktrace further down.
INFO  com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer:72 - Configuring Amazon Schema Registry Service using these properties: 
```{schemaAutoRegistrationEnabled=true, value.serializer=com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer, bootstrap.servers=b-2.kafka-cluster-dtc-priv.5xvot0.c6.kafka.us-west-2.amazonaws.com:9092,b-3.kafka-cluster-dtc-priv.5xvot0.c6.kafka.us-west-2.amazonaws.com:9092,b-1.kafka-cluster-dtc-priv.5xvot0.c6.kafka.us-west-2.amazonaws.com:9092, registry.name=dtc_avro_registry, region=us-west-2, compression=ZLIB, key.serializer=org.apache.kafka.common.serialization.StringSerializer, client.id=dmp_rawevent_processor_avro_0}```

But failing with Stacktrace
```at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getORRegisterSchemaVersionId(AWSSchemaRegistryClient.java:190)
	at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializationFacade.getOrRegisterSchemaVersion(GlueSchemaRegistrySerializationFacade.java:84)
	at com.amazonaws.services.schemaregistry.serializers.avro.AWSAvroSerializer.registerSchema(AWSAvroSerializer.java:59)
	at com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer.serialize(AWSKafkaAvroSerializer.java:93)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:60)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:884)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:846)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:733)
	at com.nanigans.kafka.producer.Producer.sendMessage(Producer.java:256)
	at com.nanigans.dmp.rawevents.attributedevents.AttributedEventCallback.setSequenceAndSend(AttributedEventCallback.java:367)
	at com.nanigans.dmp.rawevents.attributedevents.AttributedEventCallback.sendToKafka(AttributedEventCallback.java:353)
	at com.nanigans.dmp.rawevents.attributedevents.AttributedEventCallback.resolveRawPixelEvents(AttributedEventCallback.java:293)
	at com.nanigans.dmp.rawevents.attributedevents.AttributedEventCallback.processEvents(AttributedEventCallback.java:213)
	at com.nanigans.dmp.rawevents.attributedevents.AttributedEventCallback.processRecordBatch(AttributedEventCallback.java:149)
	at com.nanigans.kafka.consumer.pool.ConsumerPoolPartition$CascadePartitionedConsumerThread.dispatchRecordsToCallbacks(ConsumerPoolPartition.java:227)
	at com.nanigans.kafka.consumer.pool.ConsumerPoolPartition$CascadePartitionedConsumerThread.run(ConsumerPoolPartition.java:159)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Failed to get schemaVersionId by schema definition for schema name = pixel_events_organic 
	at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getSchemaVersionIdByDefinition(AWSSchemaRegistryClient.java:136)
	at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getORRegisterSchemaVersionId(AWSSchemaRegistryClient.java:167)
	... 16 common frames omitted
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: readHandshakeRecord
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:205)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:133)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:159)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:112)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.glue.DefaultGlueClient.getSchemaByDefinition(DefaultGlueClient.java:6710)
	at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getSchemaVersionIdByDefinition(AWSSchemaRegistryClient.java:132)
	... 17 common frames omitted
Caused by: javax.net.ssl.SSLException: readHandshakeRecord
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1325)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory.connectSocket(SdkTlsSocketFactory.java:113)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)
	at com.sun.proxy.$Proxy16.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:253)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:106)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:232)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:229)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:76)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	... 40 common frames omitted
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
		... 77 common frames omitted
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(SSLSocketOutputRecord.java:221)
	at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(OutputRecord.java:162)
	at java.base/sun.security.ssl.ChangeCipherSpec$T10ChangeCipherSpecProducer.produce(ChangeCipherSpec.java:118)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.onProduceFinished(Finished.java:395)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.produce(Finished.java:379)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	... 78 common frames omitted```

**Comment by dsingh-nan** [comment]
I have tried using version `1.00` and `1.0.1` both for `software.amazon.glue:schema-registry-serde`

**Comment by blacktooth** [comment]
Hi,

Are you able to invoke Glue Schema Registry APIs from the environment / server where you are running the above producer? You can try using the AWS CLI to test it. 

```
aws glue list-registries --region us-west-2

aws glue get-schema-version --schema-id "RegistryName=dtc_avro_registry,SchemaName=pixel_events_organic" --schema-version-number "VersionNumber=1"
```

The schema registry SerDe library invokes Glue APIs as part of serialization / deserialization.

**Comment by dsingh-nan** [comment]
Yes, I was able to 


`aws glue list-registries --region us-west-2`
```
{
  "Registries": [
  {
    "RegistryName": "dtc_avro_registry",
    "RegistryArn": "arn:aws:glue:us-west-2:012732009581:registry/dtc_avro_registry",
    "Description": "dtc Avro registry",
    "Status": "AVAILABLE",
    "CreatedTime": "2021-03-10T20:17:20.992Z",
    "UpdatedTime": "2021-03-10T20:17:20.992Z"
  }
  ]
 }
```

```
aws glue get-schema-version --schema-id "RegistryName=dtc_avro_registry,SchemaName=pixel_events_organic" --schema-version-number "VersionNumber=1"
```

```
An error occurred (EntityNotFoundException) when calling the GetSchemaVersion operation: Schema is not found. RegistryName: dtc_avro_registry, SchemaName: pixel_events_organic, SchemaArn: null
```

**Comment by blacktooth** [comment]
Do you mind sharing more information on what environment you are using to call SchemaRegistry service? From the error message, it looks like a SSL issue. Are you able to invoke other AWS services from this environment?

**Comment by blacktooth** [comment]
We haven't heard back. Please feel free to re-open if you are still facing this.

**Comment by k-chainalysis** [comment]
I had this same error calling Schema Registry from Lambda execution, and sure enough the execution role did not have IAM permissions to call Schema Registry. Thanks for the tip!

**Comment by Paolo-de-vathaire** [comment]
@blacktooth Sorry to revive this old thread but it seems appropriate, I'm facing the same error as @skydeep-9.
Using `aws glue list-registries --region eu-central-1` , I can also get the schema by id but I need to add the region to the command you provided, otherwise aws cli doesn't find it  and returns `EntityNotFoundException`.
I could work around that using aws CLI by setting my default region to `eu-central-1` but not with this lib.
Looking at the `AWSSchemaRegistryClient.getSchemaVersionIdByDefinition` method, it seems region is not sent as part of the query.

I'm correctly setting schema, registry and region as properties : 
```
configProps.put(AWSSchemaRegistryConstants.AWS_REGION, "eu-central-1");
configProps.put(AWSSchemaRegistryConstants.REGISTRY_NAME, "XXX");
configProps.put(AWSSchemaRegistryConstants.SCHEMA_NAME, "XXX");
```

I'm using I'm `SASL_SSL` with `AWS_MSK_IAM` to authenticate to AWS services.
Also this is the dependency I'm using to access Glue registry : 
```
<dependency>
            <groupId>software.amazon.glue</groupId>
            <artifactId>schema-registry-kafkastreams-serde</artifactId>
            <version>1.1.18</version>
</dependency>
```

Is that a simple bug or did I miss something ?
