### ISSUE TITLE
JSON Converter is not working with Kafka connect

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [awslabs/aws-glue-schema-registry#66]
Im using a kafka connect(debezium) to use the Glue schema registry.

I have built with the mvn, and the Avro format worked well, then I want to use JSON format for the registry, 

### connector config:

```json
{
	"name": "mysql-connector-01",
	"config": {
		"name": "mysql-connector-01",
		"connector.class": "io.debezium.connector.mysql.MySqlConnector",
		"database.server.id": "1",
		"tasks.max": "1",
		"database.history.kafka.bootstrap.servers": "XXXXX",
		"database.history.kafka.topic": "mysql-db01.schema-changes.mysql",
		"database.server.name": "mysql-db01",
		"database.hostname": "XXXX",
		"database.port": "3306",
		"database.user": "root",
		"database.password": "XXXX",
		"database.whitelist": "bhuvi",
		"transforms": "unwrap",
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
		"transforms.unwrap.add.source.fields": "ts_ms",
		"tombstones.on.delete": false,
		"key.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter",
		"key.converter.schemas.enable": "false",
		"internal.key.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter",
		"internal.key.converter.schemas.enable": "false",
		"internal.value.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter",
		"internal.value.converter.schemas.enable": "false",
		"value.converter": "com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter",
		"value.converter.schemas.enable": "true",
		"value.converter.region": "ap-south-1",
		"key.converter.region": "ap-south-1",
		"key.converter.schemaAutoRegistrationEnabled": "true",
		"value.converter.schemaAutoRegistrationEnabled": "true",
		"value.converter.avroRecordType": "GENERIC_RECORD",
		"key.converter.registry.name": "bhuvi-debezium",
		"value.converter.registry.name": "bhuvi-debezium",
		"key.converter.dataFormat": "JSON",
		"value.converter.dataFormat": "JSON",
		"snapshot.mode": "initial"
	}
}
```

Error message:

```js
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: [2021-08-03 09:13:39,342] ERROR WorkerSourceTask{id=mysql-connector-01-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:184)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: java.lang.NoSuchMethodError: scala.collection.immutable.Map$.apply(Lscala/collection/Seq;)Lscala/collection/GenMap;
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.kjetland.jackson.jsonSchema.JsonSchemaConfig$.<init>(JsonSchemaGenerator.scala:38)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.kjetland.jackson.jsonSchema.JsonSchemaConfig$.<clinit>(JsonSchemaGenerator.scala)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.scala:283)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.json.JsonSerializer.<init>(JsonSerializer.java:67)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializerFactory.lambda$getInstance$1(GlueSchemaRegistrySerializerFactory.java:52)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializerFactory.getInstance(GlueSchemaRegistrySerializerFactory.java:52)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializationFacade.getSchemaDefinition(GlueSchemaRegistrySerializationFacade.java:154)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer.prepareInput(GlueSchemaRegistryKafkaSerializer.java:147)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer.serialize(GlueSchemaRegistryKafkaSerializer.java:103)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter.fromConnectData(JsonSchemaConverter.java:140)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:295)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:295)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:324)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: at java.lang.Thread.run(Thread.java:748)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: [2021-08-03 09:13:39,352] INFO Stopping down connector (io.debezium.connector.common.BaseSourceTask:238)
Aug  3 09:13:39 ip-172-30-32-13 connect-distributed: [2021-08-03 09:13:39,402] INFO Stopped reading binlog after 0 events, no new offset was recorded (io.debezium.connector.mysql.MySqlStreamingChangeEventSource:1173)
```

Then I tried with replacing the `key.converter.dataFormat` and `value.converter.dataFormat` to lower case `json`, after that I'm getting this error.

```js
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: [2021-08-03 09:22:11,124] ERROR WorkerSourceTask{id=mysql-connector-01-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:184)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: java.lang.NoClassDefFoundError: Could not initialize class com.kjetland.jackson.jsonSchema.JsonSchemaConfig$
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.scala:283)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.json.JsonSerializer.<init>(JsonSerializer.java:67)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializerFactory.lambda$getInstance$1(GlueSchemaRegistrySerializerFactory.java:52)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializerFactory.getInstance(GlueSchemaRegistrySerializerFactory.java:52)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistrySerializationFacade.getSchemaDefinition(GlueSchemaRegistrySerializationFacade.java:154)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer.prepareInput(GlueSchemaRegistryKafkaSerializer.java:147)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer.serialize(GlueSchemaRegistryKafkaSerializer.java:103)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at com.amazonaws.services.schemaregistry.kafkaconnect.jsonschema.JsonSchemaConverter.fromConnectData(JsonSchemaConverter.java:140)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:295)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:295)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:324)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: at java.lang.Thread.run(Thread.java:748)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: [2021-08-03 09:22:11,126] INFO Stopping down connector (io.debezium.connector.common.BaseSourceTask:238)
Aug  3 09:22:11 ip-172-30-32-13 connect-distributed: [2021-08-03 09:22:11,138] INFO Stopped reading binlog after 0 events, no new offset was recorded (io.debezium.connector.mysql.MySqlStreamingChangeEventSource:1173)
```

**Comment by BhuviTheDataGuy** [comment]
Fixed it by using `key.converter` as string convertor.
